{"name": "Register valid account - security invalid", "status": "skipped", "statusDetails": {"message": "XFAIL EXPECTED LOGIN FAILURE\n\nselenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16", "trace": "driver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"04856bff-26cd-46c7-a96e-9911798d7bc4\")>\n\n    @allure.epic('Test Registration')\n    @allure.id(19)\n    @allure.title('Register valid account - security invalid')\n    @allure.description(\"Making sure accounts can't be accessed with no valid security code\")\n    @allure.severity(allure.severity_level.CRITICAL)\n    @pytest.mark.xfail(condition=lambda: True, reason='EXPECTED LOGIN FAILURE')\n    def test_sign_up_with_existing_account_security_invalid(driver):\n        signup = Rp.SignupPage(driver)\n        with allure.step('Creating a valid account with an invalid security number'):\n>           signup.sign_up(True, True, False, True, True, True, False)\n\nTest_Registration.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nProject_folder\\pages\\Registration_pages.py:91: in sign_up\n    SignupPage.click_restaurant(self)\nProject_folder\\pages\\Registration_pages.py:51: in click_restaurant\n    self.wait_for_clickable(SignupPage.RESTAURANTS).click()\nProject_folder\\pages\\common_page.py:15: in wait_for_clickable\n    return self._wait.until(U.ec.element_to_be_clickable(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"04856bff-26cd-46c7-a96e-9911798d7bc4\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x000001A77215BB00>, message = ''\n\n    def until(self, method, message: str = \"\"):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5\nE       element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n\nTRADO-interpreter\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:95: TimeoutException"}, "description": "Making sure accounts can't be accessed with no valid security code", "steps": [{"name": "Creating a valid account with an invalid security number", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5\nelement.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16\n\n", "trace": "  File \"C:\\Users\\liad\\Documents\\GitHub\\Trado-Testing-project\\Test_Registration.py\", line 44, in test_sign_up_with_existing_account_security_invalid\n    signup.sign_up(True, True, False, True, True, True, False)\n  File \"C:\\Users\\liad\\Documents\\GitHub\\Trado-Testing-project\\Project_folder\\pages\\Registration_pages.py\", line 91, in sign_up\n    SignupPage.click_restaurant(self)\n  File \"C:\\Users\\liad\\Documents\\GitHub\\Trado-Testing-project\\Project_folder\\pages\\Registration_pages.py\", line 51, in click_restaurant\n    self.wait_for_clickable(SignupPage.RESTAURANTS).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\liad\\Documents\\GitHub\\Trado-Testing-project\\Project_folder\\pages\\common_page.py\", line 15, in wait_for_clickable\n    return self._wait.until(U.ec.element_to_be_clickable(locator))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\liad\\Documents\\GitHub\\Trado-Testing-project\\TRADO-interpreter\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 95, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1680022504077, "stop": 1680022517545}], "start": 1680022504077, "stop": 1680022517548, "uuid": "14d008b8-9060-49ad-98fd-1f19f6d9bb61", "historyId": "7e3e09ce59dc3e10b6501fdd88a8bc30", "testCaseId": "166022b68c224510a8c6c53e66448028", "fullName": "Test_Registration#test_sign_up_with_existing_account_security_invalid", "labels": [{"name": "severity", "value": "critical"}, {"name": "epic", "value": "Test Registration"}, {"name": "as_id", "value": 19}, {"name": "tag", "value": "@pytest.mark.xfail(condition=<function <lambda> at 0x000001A7718C6700>, reason='EXPECTED LOGIN FAILURE')"}, {"name": "suite", "value": "Test_Registration"}, {"name": "host", "value": "TWEEJ5"}, {"name": "thread", "value": "18924-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Test_Registration"}]}